### PR TITLE
contact page1

### PR DESCRIPTION
**Pull request by TuyizeeAnastase**
Contact Page

### CODE REVIEW

**Comment by TuyizeeAnastase** [comment]
that's all for header and footer before adding contact Me content

**Comment by Ntwali-Josue** [comment]
Woow it's cool, lots of effects and edits..nice!

**Comment by TuyizeeAnastase** [comment]
thank you patern!

**Comment by TuyizeeAnastase** [comment]
@ceelogre can you get this? for reviews

**Pull request merged**
